-- Migration 002: posted/unposted transactions + employee PIN login.
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New query).

-- ── Feature 1: posted vs unposted (training) transactions ────────────────
-- Existing rows are treated as real transactions, so they are backfilled to
-- posted = true; only sales recorded after this migration default to false
-- until explicitly posted at the register.
alter table public.sales
  add column if not exists posted boolean not null default false;

update public.sales set posted = true;

-- ── Feature 4: employees with 4-digit PIN login ───────────────────────────
-- NOTE: PINs are stored in plaintext for simplicity. Hash them (e.g. bcrypt
-- via an edge function, or pgcrypto's crypt()) before using with real staff.
create table if not exists public.employees (
  id          bigint primary key generated by default as identity,
  name        text not null,
  pin         text not null,
  role        text not null default 'staff' check (role in ('owner', 'staff')),
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

-- Seeded owner account so you are not locked out. Change this PIN after
-- your first login (Admin page → Employees).
insert into public.employees (name, pin, role)
select 'Owner', '9999', 'owner'
where not exists (select 1 from public.employees where role = 'owner');
