-- Reference schema assumed by src/lib/inventoryApi.js, salesApi.js, auditLogApi.js.
-- Tables were reported as already existing; if your actual column names differ,
-- either rename your columns to match this file, or adjust the toRow/fromRow
-- mappers in src/lib/*.js to match your real schema.

create table if not exists public.inventory (
  id          bigint primary key generated by default as identity,
  name        text not null,
  price       numeric not null default 0,
  category    text,
  tax_cat     text,
  stock       integer not null default 0,
  barcode     text,
  emoji       text,
  cost        numeric default 0,
  reorder_at  integer default 0
);

create table if not exists public.sales (
  id          text primary key,
  time        timestamptz not null default now(),
  province    text not null,
  method      text not null,
  sub         numeric not null default 0,
  gst         numeric not null default 0,
  pst         numeric not null default 0,
  hst         numeric not null default 0,
  total       numeric not null default 0,
  cash_given  numeric,
  change      numeric,
  surcharge   numeric not null default 0
);

create table if not exists public.sale_items (
  id          bigint primary key generated by default as identity,
  sale_id     text references public.sales(id) on delete cascade,
  item_id     bigint,
  name        text,
  emoji       text,
  category    text,
  tax_cat     text,
  price       numeric,
  cost        numeric default 0,
  qty         integer not null,
  subtotal    numeric not null,
  gst         numeric not null default 0,
  pst         numeric not null default 0,
  hst         numeric not null default 0,
  line_total  numeric not null
);

create table if not exists public.audit_log (
  id          bigint primary key generated by default as identity,
  time        timestamptz not null default now(),
  editor      text,
  item        text,
  field       text,
  from_value  text,
  to_value    text
);
